export const ALL_EXPERIENCES_REQUEST = "ALL_EXPERIENCES_REQUEST";
export const ALL_EXPERIENCES_SUCCESS = "ALL_EXPERIENCES_SUCCESS";
export const ALL_EXPERIENCES_FAIL = "ALL_EXPERIENCES_FAIL";

export const EXPERIENCE_DETAILS_REQUEST = "EXPERIENCE_DETAILS_REQUEST";
export const EXPERIENCE_DETAILS_SUCCESS = "EXPERIENCE_DETAILS_SUCCESS";
export const EXPERIENCE_DETAILS_FAIL = "EXPERIENCE_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
