export const FETCH_ALL_EXPERIENCES = 'FETCH_ALL_EXPERIENCES'; // naming the action with a verb that will make it more readable
export const FETCH_ALL_EXPERIENCES_SUCCESS = 'FETCH_ALL_EXPERIENCES_SUCCESS';
export const FETCH_ALL_EXPERIENCES_FAIL = 'FETCH_ALL_EXPERIENCES_FAIL';

export const FETCH_EXPERIENCE_DETAILS = 'FETCH_EXPERIENCE_DETAILS';
export const FETCH_EXPERIENCE_DETAILS_SUCCESS =
  'FETCH_EXPERIENCE_DETAILS_SUCCESS';
export const FETCH_EXPERIENCE_DETAILS_FAIL = 'FETCH_EXPERIENCE_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
