export const FETCH_ALL_EXPERIENCES = "FETCH_ALL_EXPERIENCES"; // naming the action with a verb that will make it more readable
export const FETCH_ALL_EXPERIENCES_SUCCESS = "FETCH_ALL_EXPERIENCES_SUCCESS";
export const FETCH_ALL_EXPERIENCES_FAIL = "FETCH_ALL_EXPERIENCES_FAIL";

export const FETCH_EXPERIENCE_DETAILS = "FETCH_EXPERIENCE_DETAILS";
export const FETCH_EXPERIENCE_DETAILS_SUCCESS =
  "FETCH_EXPERIENCE_DETAILS_SUCCESS";
export const FETCH_EXPERIENCE_DETAILS_FAIL = "FETCH_EXPERIENCE_DETAILS_FAIL";

export const ADD_EXPERIENCE = "ADD_EXPERIENCE";
export const ADD_EXPERIENCE_SUCCESS = "ADD_EXPERIENCE_SUCCESS";
export const ADD_EXPERIENCE_FAIL = "ADD_EXPERIENCE_FAIL";

export const DELETE_EXPERIENCE = "ADD_EXPERIENCE";
export const DELETE_EXPERIENCE_SUCCESS = "ADD_EXPERIENCE_SUCCESS";
export const DELETE_EXPERIENCE_FAIL = "ADD_EXPERIENCE_FAIL";
export const UPDATE_EXPERIENCE_SUCCESS = "UPDATE_EXPERIENCE_SUCCESS";
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";
export const UPDATE_EXPERIENCE_FAIL = "UPDATE_EXPERIENCE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
